In [1]:
# %load NumPy - Chapter 4.py

#Your First Numpy Array

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [153]:
#Turning a webpage into data using BeautifulSoup: getting the text

# Import packages
from urllib.request import urlopen
from bs4 import BeautifulSoup

# Specify url: url
url = 'http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights'

page = urlopen(url)

soup = BeautifulSoup(page, 'html.parser')

table = soup.find('table', {'class':'wikitable'}) # On inspecte le code HTML et on choisit la class souhaitée

column_names = []
col_names = table.findAll('th') # On chcer les noms des colonnes du tableau
for i in col_names:
    cols = i.text
    column_names.append(cols)

column_names = [x.strip(' ') for x in column_names] # On supprime les espaces en trop dans la liste
column_names[-1] = 'age' # On réecrit proprement age\n

data=[]
rows = table.findAll('tr')
for row in rows:
    cols = row.findAll('td')
    cols = [i.text.strip() for i in cols]
    data.append([i for i in cols if i])

data.pop(0) # Os supprime la 1ère liste qui est vide

import pandas as pd
df = pd.DataFrame(data, columns=column_names)

df['Height(inches)'] = df['Height(inches)'].astype(int) #On change les types des colonnes numériques
df['Weight(pounds)'] = df['Weight(pounds)'].astype(float)
df['age'] = df['age'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1034 entries, 0 to 1033
Data columns (total 6 columns):
Name              1034 non-null object
Team              1034 non-null object
Position          1034 non-null object
Height(inches)    1034 non-null int64
Weight(pounds)    1034 non-null float64
age               1033 non-null float64
dtypes: float64(2), int64(1), object(3)
memory usage: 48.5+ KB


In [132]:
#Baseball players' height

# height is available as a regular list
height = df['Height(inches)']

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [135]:
#Baseball player's BMI

# height and weight are available as a regular lists
weight = df['Weight(pounds)']

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


In [139]:
#Lightweight baseball players

# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

[False False False ... False False False]


In [140]:
#Subsetting Numpy Arrays

# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 50
print(np_weight[50])

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height[100:111])

195.0
[73 72 74 73 74 72 73 69 72 73 75]


In [141]:
#Your First 2D Numpy Array

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [142]:
#Baseball data in 2D form

# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [143]:
#Subsetting 2D Numpy Arrays

# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123, 0])

IndexError: index 49 is out of bounds for axis 0 with size 4

In [144]:
#2D Arithmetic

# baseball is available as a regular list of lists

# update is available as 2D Numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and update
print(np_baseball + update)

# Create Numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

NameError: name 'update' is not defined

In [145]:
#Average versus median

# np_baseball is available

# Import numpy
import numpy as np

# Create np_height from np_baseball
np_height = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

198.25
199.0


In [146]:
#Explore the baseball data

# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


In [152]:
#Blend it all together

# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(height)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: nan
Median height of other players: 74.0
