In [2]:
# %load Chapter 2 - Default arguments, variable-length arguments and scope.py

#Chapter 2 Default arguments, variable-length arguments and scope

#The keyword global

# Create a string: team
team = "teen titans"

# Define change_team()
def change_team():
    """Change the value of the global variable team."""

    # Use team in global scope
    global team

    # Change the value of team in global: team
    team="justice league"

# Print team
print(team)

# Call change_team()
change_team()

# Print team
print(team)

teen titans
justice league


In [3]:
#Nested Functions I

# Define three_shouts
def three_shouts(word1, word2, word3):
    """Returns a tuple of strings
    concatenated with '!!!'."""

    # Define inner
    def inner(word):
        """Returns a string concatenated with '!!!'."""
        return word + '!!!'

    # Return a tuple of strings
    return (inner(word1), inner(word2), inner(word3))

# Call three_shouts() and print
print(three_shouts('a', 'b', 'c'))

('a!!!', 'b!!!', 'c!!!')


In [4]:
#Nested Functions II

# Define echo
def echo(n):
    """Return the inner_echo function."""

    # Define inner_echo
    def inner_echo(word1):
        """Concatenate n copies of word1."""
        echo_word = word1 * n
        return echo_word

    # Return inner_echo
    return inner_echo

# Call echo: twice
twice = echo(2)

# Call echo: thrice
thrice = echo(3)

# Call twice() and thrice() then print
print(twice('hello'), thrice('hello'))

hellohello hellohellohello


In [5]:
#The keyword nonlocal and nested functions

# Define echo_shout()
def echo_shout(word):
    """Change the value of a nonlocal variable"""
    
    # Concatenate word with itself: echo_word
    echo_word = word*2
    
    #Print echo_word
    print(echo_word)
    
    # Define inner function shout()
    def shout():
        """Alter a variable in the enclosing scope"""
        
        #Use echo_word in nonlocal scope
        nonlocal echo_word
        
        #Change echo_word to echo_word concatenated with '!!!'
        echo_word = echo_word + '!!!'
    
    # Call function shout()
    shout()

    #Print echo_word
    print(echo_word)

#Call function echo_shout() with argument 'hello'    
echo_shout('hello')

hellohello
hellohello!!!


In [6]:
#Functions with one default argument

# Define shout_echo
def shout_echo(word1, echo=1):
    """Concatenate echo copies of word1 and three
     exclamation marks at the end of the string."""

    # Concatenate echo copies of word1 using *: echo_word
    echo_word = word1*echo

    # Concatenate '!!!' to echo_word: shout_word
    shout_word = echo_word + '!!!'

    # Return shout_word
    return shout_word

# Call shout_echo() with "Hey": no_echo
no_echo =shout_echo("Hey")

# Call shout_echo() with "Hey" and echo=5: with_echo
with_echo = shout_echo("Hey",echo=5)

# Print no_echo and with_echo
print(no_echo)
print(with_echo)

Hey!!!
HeyHeyHeyHeyHey!!!


In [7]:
#Functions with multiple default arguments

# Define shout_echo
def shout_echo(word1, echo=1, intense=False):
    """Concatenate echo copies of word1 and three
    exclamation marks at the end of the string."""

    # Concatenate echo copies of word1 using *: echo_word
    echo_word = word1 * echo

    # Capitalize echo_word if intense is True
    if intense is True:
        # Capitalize and concatenate '!!!': echo_word_new
        echo_word_new = echo_word.upper() + '!!!'
    else:
        # Concatenate '!!!' to echo_word: echo_word_new
        echo_word_new = echo_word + '!!!'

    # Return echo_word_new
    return echo_word_new

# Call shout_echo() with "Hey", echo=5 and intense=True: with_big_echo
with_big_echo = shout_echo("Hey",echo=5 ,intense=True)

# Call shout_echo() with "Hey" and intense=True: big_no_echo
big_no_echo = shout_echo("Hey", intense=True)

# Print values
print(with_big_echo)
print(big_no_echo)

HEYHEYHEYHEYHEY!!!
HEY!!!


In [8]:
#Function with variable-length arguments (*args)

# Define gibberish
def gibberish(*args):
    """Concatenate strings in *args together."""

    # Initialize an empty string: hodgepodge
    hodgepodge=""

    # Concatenate the strings in args
    for word in args:
        hodgepodge += word

    # Return hodgepodge
    return hodgepodge

# Call gibberish() with one string: one_word
one_word = gibberish("luke")

# Call gibberish() with five strings: many_words
many_words = gibberish("luke", "leia", "han", "obi", "darth")

# Print one_word and many_words
print(one_word)
print(many_words)

luke
lukeleiahanobidarth


In [9]:
#Function with variable-length keyword arguments (**kwargs)

# Define report_status
def report_status(**kwargs):
    """Print out the status of a movie character."""

    print("\nBEGIN: REPORT\n")

    # Print a formatted status report
    for key, value in kwargs.items():
        print(key + ": " + value)

    print("\nEND REPORT")

# First call to report_status()
report_status(name="luke", affiliation="jedi", status="missing")

# Second call to report_status()
report_status(name="anakin", affiliation="sith lord", status="deceased")


BEGIN: REPORT

name: luke
affiliation: jedi
status: missing

END REPORT

BEGIN: REPORT

name: anakin
affiliation: sith lord
status: deceased

END REPORT


In [2]:
import os

In [3]:
os.chdir("c:\\Users\\mmonn\\Desktop\\DataCamp\\Data Scientist with Python\\Data Scientist with Python\\Courses\\Python Data Science Toolbox (Part 1)")

In [4]:
#Bringing it all together (1)

import pandas as pd 
import numpy
tweets_df = pd.read_csv('Datasets\\tweets.csv')

In [5]:
tweets_df.columns

Index(['contributors', 'coordinates', 'created_at', 'entities',
       'extended_entities', 'favorite_count', 'favorited', 'filter_level',
       'geo', 'id', 'id_str', 'in_reply_to_screen_name',
       'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str', 'is_quote_status',
       'lang', 'place', 'possibly_sensitive', 'quoted_status',
       'quoted_status_id', 'quoted_status_id_str', 'retweet_count',
       'retweeted', 'retweeted_status', 'source', 'text', 'timestamp_ms',
       'truncated', 'user'],
      dtype='object')

In [6]:
tweets_df.head()

contributors  coordinates                      created_at  \
0           NaN          NaN  Tue Mar 29 23:40:17 +0000 2016   
1           NaN          NaN  Tue Mar 29 23:40:17 +0000 2016   
2           NaN          NaN  Tue Mar 29 23:40:17 +0000 2016   
3           NaN          NaN  Tue Mar 29 23:40:17 +0000 2016   
4           NaN          NaN  Tue Mar 29 23:40:17 +0000 2016   

                                            entities  \
0  {'hashtags': [], 'user_mentions': [{'screen_na...   
1  {'hashtags': [{'text': 'cruzsexscandal', 'indi...   
2  {'hashtags': [], 'user_mentions': [], 'symbols...   
3  {'hashtags': [], 'user_mentions': [], 'symbols...   
4  {'hashtags': [], 'user_mentions': [{'screen_na...   

                                   extended_entities  favorite_count  \
0  {'media': [{'sizes': {'large': {'w': 1024, 'h'...               0   
1  {'media': [{'sizes': {'large': {'w': 500, 'h':...               0   
2                                                NaN               0   
3                                                NaN               0   
4                                                NaN               0   

   favorited filter_level  geo                  id  ...  quoted_status_id  \
0      False          low  NaN  714960401759387648  ...               NaN   
1      False          low  NaN  714960401977319424  ...               NaN   
2      False          low  NaN  714960402426236928  ...               NaN   
3      False          low  NaN  714960402367561730  ...      7.149239e+17   
4      False          low  NaN  714960402149416960  ...               NaN   

  quoted_status_id_str  retweet_count  retweeted  \
0                  NaN              0      False   
1                  NaN              0      False   
2                  NaN              0      False   
3         7.149239e+17              0      False   
4                  NaN              0      False   

                                    retweeted_status  \
0  {'retweeted': False, 'text': ".@krollbondratin...   
1  {'retweeted': False, 'text': '@dmartosko Cruz ...   
2                                                NaN   
3                                                NaN   
4  {'retweeted': False, 'text': 'The anti-America...   

                                              source  \
0  <a href="http://twitter.com" rel="nofollow">Tw...   
1  <a href="http://twitter.com" rel="nofollow">Tw...   
2  <a href="http://www.facebook.com/twitter" rel=...   
3  <a href="http://twitter.com/download/android" ...   
4  <a href="http://twitter.com/download/iphone" r...   

                                                text   timestamp_ms truncated  \
0  RT @bpolitics: .@krollbondrating's Christopher...  1459294817758     False   
1  RT @HeidiAlpine: @dmartosko Cruz video found.....  1459294817810     False   
2  Njihuni me Zonjën Trump !!! | Ekskluzive https...  1459294817917     False   
3  Your an idiot she shouldn't have tried to grab...  1459294817903     False   
4  RT @AlanLohner: The anti-American D.C. elites ...  1459294817851     False   

                                                user  
0  {'utc_offset': 3600, 'profile_image_url_https'...  
1  {'utc_offset': None, 'profile_image_url_https'...  
2  {'utc_offset': 7200, 'profile_image_url_https'...  
3  {'utc_offset': None, 'profile_image_url_https'...  
4  {'utc_offset': -18000, 'profile_image_url_http...  

[5 rows x 31 columns]

In [33]:
rand_arr = np.random.randint(low=2, high=6, size=10, dtype=int)

In [34]:
dummy_dict = {'pew': rand_arr}

In [35]:
dummy_df = pd.DataFrame(dummy_dict)

In [38]:
y = np.bincount(rand_arr)
ii = np.nonzero(y)[0]

In [48]:
rand_arr

array([2, 2, 5, 3, 2, 4, 5, 5, 3, 3])

In [47]:
y

array([0, 0, 3, 3, 1, 3], dtype=int64)

In [50]:
np.nonzero()

(array([2, 3, 4, 5], dtype=int64),)

In [43]:
ground_truth = dict(zip(ii, y[ii]))

In [44]:
ground_truth

{2: 3, 3: 3, 4: 1, 5: 3}

In [45]:
res_dict = {}
for key in dummy_df['pew']:
    if key in res_dict.keys():
        res_dict[key] +=1
    else:
        res_dict[key] =1

In [46]:
res_dict

{2: 3, 5: 3, 3: 3, 4: 1}

In [51]:
# Define count_entries()
def count_entries(df,col_name='lang'):
    """Return a dictionary with counts of
    occurrences as value for each key."""

    # Initialize an empty dictionary: cols_count
    cols_count = {}

    # Extract column from DataFrame: col
    col = df[col_name]
    
    # Iterate over the column in DataFrame
    for entry in col:

        # If entry is in cols_count, add 1
        if entry in cols_count.keys():
            cols_count[entry] += 1

        # Else add the entry to cols_count, set the value to 1
        else:
            cols_count[entry] = 1

    # Return the cols_count dictionary
    return cols_count

# Call count_entries(): result1
result1 = count_entries(tweets_df,'lang')

# Call count_entries(): result2
result2 = count_entries(tweets_df,'source')

# Print result1 and result2
print(result1)
print(result2)

{'en': 97, 'et': 1, 'und': 2}
{'<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>': 24, '<a href="http://www.facebook.com/twitter" rel="nofollow">Facebook</a>': 1, '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>': 26, '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>': 33, '<a href="http://www.twitter.com" rel="nofollow">Twitter for BlackBerry</a>': 2, '<a href="http://www.google.com/" rel="nofollow">Google</a>': 2, '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>': 6, '<a href="http://linkis.com" rel="nofollow">Linkis.com</a>': 2, '<a href="http://rutracker.org/forum/viewforum.php?f=93" rel="nofollow">newzlasz</a>': 2, '<a href="http://ifttt.com" rel="nofollow">IFTTT</a>': 1, '<a href="http://www.myplume.com/" rel="nofollow">Plume\xa0for\xa0Android</a>': 1}


In [13]:
#Bringing it all together (2)

# Define count_entries()
def count_entries(df, *args):
    """Return a dictionary with counts of
    occurrences as value for each key."""
    
    #Initialize an empty dictionary: cols_count
    cols_count = {}
    
    # Iterate over column names in args
    for col_name in args:
    
        # Extract column from DataFrame: col
        col = df[col_name]
    
        # Iterate over the column in DataFrame
        for entry in col:
    
            # If entry is in cols_count, add 1
            if entry in cols_count.keys():
                cols_count[entry] += 1
    
            # Else add the entry to cols_count, set the value to 1
            else:
                cols_count[entry] = 1

    # Return the cols_count dictionary
    return cols_count

# Call count_entries(): result1
result1 = count_entries(tweets_df, 'lang')

# Call count_entries(): result2
result2 = count_entries(tweets_df, 'lang', 'source')

# Print result1 and result2
print(result1)
print(result2)

{'en': 97, 'et': 1, 'und': 2}
{'en': 97, 'et': 1, 'und': 2, '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>': 24, '<a href="http://www.facebook.com/twitter" rel="nofollow">Facebook</a>': 1, '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>': 26, '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>': 33, '<a href="http://www.twitter.com" rel="nofollow">Twitter for BlackBerry</a>': 2, '<a href="http://www.google.com/" rel="nofollow">Google</a>': 2, '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>': 6, '<a href="http://linkis.com" rel="nofollow">Linkis.com</a>': 2, '<a href="http://rutracker.org/forum/viewforum.php?f=93" rel="nofollow">newzlasz</a>': 2, '<a href="http://ifttt.com" rel="nofollow">IFTTT</a>': 1, '<a href="http://www.myplume.com/" rel="nofollow">Plume\xa0for\xa0Android</a>': 1}
